### ISSUE TITLE
Execute command hangs after inputs collection if piped

### ISSUE THREAD

**Issue by blake-mealey** [airplanedev/cli#366]
If I pipe the output of the execute command without providing all required inputs with CLI arguments, it gets stuck between prompting for inputs and prompting "Execute: Y/n". 

For example: `airplane execute my_task.ts -o json | jq ".path"`

My tasks use Node.js

**Comment by blake-mealey** [comment]
I also cannot use any of these:

`airplane execute my_task.ts -o json > results.json`

`outputs=$(airplane execute my_task.ts -o json)`

I would like to consume these outputs for chaining during local development but this is a blocker for me.

**Comment by blake-mealey** [comment]
Thanks for the quick response! Yes that does work but unfortunately for my flow I want the user to be prompted 😛

Loving the product so far btw

**Comment by joshma** [comment]
> Yes that does work but unfortunately for my flow I want the user to be prompted

Ah, I see what you're saying now. We'll dig into the bug, sorry for the trouble!

**Comment by joshma** [comment]
Hey @blake-mealey , we have a fix out in v0.1.65 (latest version). Can you try updating and letting us know if it's not resolved? Will close for now!

**Comment by blake-mealey** [comment]
Problem is solved, thanks for the quick turn around on this!
