### ISSUE TITLE
Error: esbuild(error)

### ISSUE THREAD

**Issue by LeoAltissimo** [airplanedev/cli#759]
I updated the Airplane CLI on Windows, and now when trying to run some Js tasks locally, the error below immediately occurs. I tested it on a new task created from scratch through the CLI and got the same error. I tried a task that runs daily on the platform, and I also got the same error.

Node version: 18 (same on task.yaml)
OS: Windows 11 Home (Tested on two machines)
Airplane CLI version: 0.3.61 (2022-10-29T00:22:52Z)

```
[warning] esbuild(error): {  Could not resolve "..\\..\\proj" 0xc001465260 [{Use the relative path "./..\\..\\proj" to reference the file "proj.ts". Without the leading "./", the path "..\\..\\proj" is being interpreted as a package path instead. <nil>}] <nil>}
```

**Comment by LeoAltissimo** [comment]
Update: I installed a VM with Ubuntu, and it works with the same code. It is probably a Windows related problem only.

**Comment by calufornia** [comment]
Hi @LeoAltissimo, Windows support for local development is not well-supported right now, but adding support is one of the team's top priorities. For now, I'd recommend using a Linux VM or WSL when developing with the CLI. We'll post an update when support for Windows is out!

**Comment by leeweisberger** [comment]
This particular issue was a bug that was introduced and resolved in https://github.com/airplanedev/lib/pull/382. This should work in the latest version of the CLI
