### ISSUE TITLE
Airplane Login Issue

### ISSUE THREAD

**Issue by deepak2431** [airplanedev/cli#891]
I am not able to log in to Airplane after my team brought a subscription plan. I was previously using Airplan free trial but on migration to a new email, I am not able to Login or access my account.

The console shows this error:
![Screenshot 2023-01-09 at 12 24 17 PM](https://user-images.githubusercontent.com/44617923/211254872-24e355c7-516d-4c7a-ad67-c8b10ffc02ef.png)

**Comment by zhan-airplane** [comment]
Hi @deepak2431, we're taking a look at this issue now, we'll get back to you shortly
